site_name: Doxybook Example
theme:
  name: 'material'
markdown_extensions:
  - admonition
nav:
  - Home: /doxybook/mkdocs-material/
  - Classes: /doxybook/mkdocs-material/classes
  - Namespaces: /doxybook/mkdocs-material/namespaces
  - Modules: /doxybook/mkdocs-material/libraries
  - Files: /doxybook/mkdocs-material/files
  - Related Pages: /doxybook/mkdocs-material/pages
  - Examples: /doxybook/mkdocs-material/examples
