site_name: Doxybook Example
theme:
  name: 'flatly'
markdown_extensions:
  - admonition
nav:
  - Home: /doxybook/mkdocs-bootswatch/
  - Classes: /doxybook/mkdocs-bootswatch/Classes
  - Namespaces: /doxybook/mkdocs-bootswatch/Namespaces
  - Modules: /doxybook/mkdocs-bootswatch/Modules
  - Files: /doxybook/mkdocs-bootswatch/Files
  - Related Pages: /doxybook/mkdocs-bootswatch/Pages
  - Examples: /doxybook/mkdocs-bootswatch/Examples
